# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/apple/Desktop/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,Qt
import sys
import pymysql
import backend as db


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setEnabled(True)
        self.labelName.setGeometry(QtCore.QRect(40, 50, 140, 40))
        self.labelName.setObjectName("labelName")
        self.pushButtonItemAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonItemAll.setGeometry(QtCore.QRect(270, 10, 112, 32))
        self.pushButtonItemAll.setObjectName("pushButtonItemAll")
        self.pushButtonEquipAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEquipAll.setGeometry(QtCore.QRect(370, 10, 112, 32))
        self.pushButtonEquipAll.setObjectName("pushButtonEquipAll")
        self.labelLevel = QtWidgets.QLabel(self.centralwidget)
        self.labelLevel.setGeometry(QtCore.QRect(40, 80, 140, 16))
        self.labelLevel.setObjectName("labelLevel")
        self.labelStrength = QtWidgets.QLabel(self.centralwidget)
        self.labelStrength.setGeometry(QtCore.QRect(40, 100, 140, 16))
        self.labelStrength.setObjectName("labelStrength")
        self.labelSpeed = QtWidgets.QLabel(self.centralwidget)
        self.labelSpeed.setGeometry(QtCore.QRect(40, 120, 140, 16))
        self.labelSpeed.setObjectName("labelSpeed")
        self.labelIntelligence = QtWidgets.QLabel(self.centralwidget)
        self.labelIntelligence.setGeometry(QtCore.QRect(40, 140, 140, 16))
        self.labelIntelligence.setObjectName("labelIntelligence")
        self.labelProfession = QtWidgets.QLabel(self.centralwidget)
        self.labelProfession.setGeometry(QtCore.QRect(40, 160, 140, 16))
        self.labelProfession.setObjectName("labelhProfession")
        self.labelHequipment = QtWidgets.QLabel(self.centralwidget)
        self.labelHequipment.setGeometry(QtCore.QRect(40, 180, 140, 16))
        self.labelHequipment.setObjectName("labelHequipment")
        self.pushButtonTaskAv = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTaskAv.setGeometry(QtCore.QRect(370, 40, 112, 32))
        self.pushButtonTaskAv.setObjectName("pushButtonTaskAv")
        self.pushButtonBox = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBox.setGeometry(QtCore.QRect(540, 220, 81, 32))
        self.pushButtonBox.setObjectName("pushButtonBox")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(220, 70, 311, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)  # 设置表格的选取方式是行选取
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)  # 设置选取方式为单个选取

        self.labelErr = QtWidgets.QLabel(self.centralwidget)
        self.labelErr.setGeometry(QtCore.QRect(220, 310, 300, 16))
        self.labelErr.setObjectName("labelErr")
        self.pushButtonTaskUn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTaskUn.setGeometry(QtCore.QRect(270, 40, 112, 32))
        self.pushButtonTaskUn.setObjectName("pushButtonTaskUn")
        self.pushButtonTaskDrop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTaskDrop.setGeometry(QtCore.QRect(540, 101, 81, 31))
        self.pushButtonTaskDrop.setObjectName("pushButtonTaskDrop")
        self.pushButtonDrop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDrop.setGeometry(QtCore.QRect(540, 280, 81, 32))
        self.pushButtonDrop.setObjectName("pushButtonDrop")
        self.pushButtonChange = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonChange.setGeometry(QtCore.QRect(540, 260, 81, 32))
        self.pushButtonChange.setObjectName("pushButtonChange")
        self.pushButtonSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSubmit.setGeometry(QtCore.QRect(540, 130, 81, 32))
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.pushButtonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(40, 240, 110, 50))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.labelDetail = QtWidgets.QLabel(self.centralwidget)
        self.labelDetail.setGeometry(QtCore.QRect(170, 340, 411, 61))
        self.labelDetail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelDetail.setObjectName("labelDetail")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButtonLogin.clicked.connect(lambda:self.showRole(1))
        self.pushButtonItemAll.clicked.connect(lambda:self.viewTable('Item'))
        self.pushButtonEquipAll.clicked.connect(lambda:self.viewTable('Equipment'))
        self.pushButtonTaskAv.clicked.connect(self.viewTaskAv)
        self.pushButtonTaskUn.clicked.connect(self.viewTaskUn)
        self.tableWidget.clicked.connect(self.select)
        self.pushButtonSubmit.clicked.connect(self.submit)
        self.pushButtonTaskDrop.clicked.connect(self.giveup)
        self.pushButtonBox.clicked.connect(self.box)
        self.pushButtonChange.clicked.connect(self.equip)
        self.pushButtonDrop.clicked.connect(self.drop)

    def drop(self):
        row_index = self.tableWidget.currentIndex().row()
        id = self.tableWidget.item(row_index, 0).text()
        db.drop(id)
        self.pushButtonEquipAll.click()

    def equip(self):
        row_index = self.tableWidget.currentIndex().row()
        id = self.tableWidget.item(row_index, 0).text()
        limit = self.tableWidget.item(row_index, 4).text()
        db.equip(id,limit)
        self.pushButtonLogin.click()


    def box(self):
        db.box()
        self.pushButtonEquipAll.click()

    def select(self):
        row_index = self.tableWidget.currentIndex().row()  # 获取当前行Index
        # content= self.tableWidget.item(row_index,0).text() # item(行,列), 获取当前行第一格
        symbol = self.tableWidget.item(row_index,3).text()
        if (symbol == 'bow') or (symbol == 'stick') or (symbol == 'axe') or (symbol == 'sword'):
            content = self.tableWidget.item(row_index,6).text()
            self.labelDetail.setText("装备描述："+content)
        elif symbol == 'gem':
            content = self.tableWidget.item(row_index,5).text()
            self.labelDetail.setText("道具描述："+content)
        elif (symbol == 'save_king') or (symbol == 'save_prince') or (symbol == 'save_princess') or (symbol == 'save_yourself') or (symbol == 'save_queen'):
            content = self.tableWidget.item(row_index,8).text()
            self.labelDetail.setText("任务描述："+content)
        else:
            pass


    def submit(self):
        row_index = self.tableWidget.currentIndex().row()
        id = self.tableWidget.item(row_index, 0).text()
        db.submit(id)
        self.viewTaskAv()
    def giveup(self):
        row_index = self.tableWidget.currentIndex().row()
        id = self.tableWidget.item(row_index, 0).text()
        db.giveup(id)
        self.viewTaskUn()


    def viewTable(self,table): #获取表
        if table == 'Item':
            self.tableWidget.setHorizontalHeaderLabels(["IID", "RID", "iname", "itype", "ieffect", "idisc"])
        else:
            self.tableWidget.setHorizontalHeaderLabels(["EID", "RID", "ename", "etype", "plimit", "llimit", "edisc", "attack", "defence"])
        a = db.view(table)
        row = a[1]
        vol = a[2]
        self.tableWidget.setRowCount(row)
        self.tableWidget.setColumnCount(vol)

        for i in range(row):
            for j in range(vol):
                # 临时记录，不能直接插入表格
                temp_data =a[0][i][j]
                # 转换后可插入表格
                data = QtWidgets.QTableWidgetItem(str(temp_data))
                self.tableWidget.setItem(i, j, data)

    def viewTaskAv(self):
        self.tableWidget.setHorizontalHeaderLabels(["TID", "RID", "NID", "tname", "llimit", "plimit", "ttype", "tstatus", "tdisc"])
        a = db.viewTask('unfin')
        self.tableWidget.setRowCount(a[1])
        self.tableWidget.setColumnCount(a[2])

        for i in range(a[1]):
            for j in range(a[2]):
                # 临时记录，不能直接插入表格
                temp_data = a[0][i][j]
                # 转换后可插入表格
                data = QtWidgets.QTableWidgetItem(str(temp_data))
                self.tableWidget.setItem(i, j, data)

    def viewTaskUn(self):
        self.tableWidget.setHorizontalHeaderLabels(["TID", "RID", "NID", "tname", "llimit", "plimit", "ttype", "tstatus", "tdisc"])
        a = db.viewTask('fin')
        self.tableWidget.setRowCount(a[1])
        self.tableWidget.setColumnCount(a[2])

        for i in range(a[1]):
            for j in range(a[2]):
                # 临时记录，不能直接插入表格
                temp_data = a[0][i][j]
                # 转换后可插入表格
                data = QtWidgets.QTableWidgetItem(str(temp_data))
                self.tableWidget.setItem(i, j, data)



    def showRole(self,RID):
        data = db.role(RID)
        self.labelName.setText("昵称：一个小法师")
        self.labelLevel.setText("等级："+str(data[2]))
        self.labelStrength.setText("体质："+str(data[3]))
        self.labelSpeed.setText("敏捷："+str(data[4]))
        self.labelIntelligence.setText("智力："+str(data[5]))
        self.labelProfession.setText("职业："+data[6])
        self.labelHequipment.setText("当前装备："+data[8][0])





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "美式RPG角色管理系统"))
        self.labelName.setText(_translate("MainWindow", "昵称："))
        self.pushButtonItemAll.setText(_translate("MainWindow", "道具"))
        self.pushButtonEquipAll.setText(_translate("MainWindow", "装备"))
        self.pushButtonLogin.setText(_translate("MainWindow", "登陆"))
        self.labelLevel.setText(_translate("MainWindow", "等级："))
        self.labelStrength.setText(_translate("MainWindow", "体质："))
        self.labelSpeed.setText(_translate("MainWindow", "敏捷："))
        self.labelIntelligence.setText(_translate("MainWindow", "智力："))
        self.labelProfession.setText(_translate("MainWindow", "职业："))
        self.labelHequipment.setText(_translate("MainWindow", "拥有装备："))
        self.pushButtonTaskAv.setText(_translate("MainWindow", "进行中的任务"))
        self.pushButtonBox.setText(_translate("MainWindow", "抽奖"))
        self.pushButtonTaskUn.setText(_translate("MainWindow", "已完成的任务"))
        self.pushButtonTaskDrop.setText(_translate("MainWindow", "重新接受"))
        self.pushButtonDrop.setText(_translate("MainWindow", "丢弃"))
        self.pushButtonChange.setText(_translate("MainWindow", "装备"))
        self.pushButtonSubmit.setText(_translate("MainWindow", "提交任务"))
        self.labelErr.setText(_translate("MainWindow", ""))
        self.labelDetail.setText(_translate("MainWindow", ""))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
